set welc(msg) "Welcome to TornadoIRC, %nick. You have joined %chan where you MUST have a registered nickname to chat."
set welc(chan) "#lobby"
set welc(type) "1"

bind join - #lobby* givewelcome
proc givewelcome {nick uhost hand chan} {
global welc

set welctxt $welc(msg)
regsub -all "%nick" $welctxt "$nick" welctxt
regsub -all "%chan" $welctxt "$chan" welctxt
switch $welc(type) {
1 { puthelp "NOTICE $nick :$welctxt" }
2 { puthelp "PRIVMSG $nick :$welctxt" }
}
}
putlog "Channel Greeting - Generated by http://www.egginfo.org - Frostbyte"
